// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get_my_profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.100.0";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const anon = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, anon, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function textResult(text, isError = false) {
  return { content: [{ type: "text", text }], isError };
}
function jsonResult(data) {
  return {
    content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
    structuredContent: { data }
  };
}

// src/lib/mcp/tools/get_my_profile.ts
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "\u041C\u0435\u043D\u0456\u04A3 \u043F\u0440\u043E\u0444\u0438\u043B\u0456\u043C",
  description: "\u0410\u0493\u044B\u043C\u0434\u0430\u0493\u044B \u049B\u043E\u0441\u044B\u043B\u0493\u0430\u043D \u043F\u0430\u0439\u0434\u0430\u043B\u0430\u043D\u0443\u0448\u044B\u043D\u044B\u04A3 BilimApp \u043F\u0440\u043E\u0444\u0438\u043B\u0456\u043D (\u0430\u0442\u044B-\u0436\u04E9\u043D\u0456, \u0440\u04E9\u043B\u0456, \u043C\u0435\u043A\u0442\u0435\u0431\u0456, \u0441\u044B\u043D\u044B\u0431\u044B) \u049B\u0430\u0439\u0442\u0430\u0440\u0430\u0434\u044B.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return textResult("\u0410\u0443\u0442\u0435\u043D\u0442\u0438\u0444\u0438\u043A\u0430\u0446\u0438\u044F \u049B\u0430\u0436\u0435\u0442.", true);
    const sb = supabaseForUser(ctx);
    const uid = ctx.getUserId();
    const { data: profile, error: pErr } = await sb.from("profiles").select("*").eq("user_id", uid).maybeSingle();
    if (pErr) return textResult(pErr.message, true);
    const { data: roles } = await sb.from("user_roles").select("role").eq("user_id", uid);
    return jsonResult({ profile, roles: roles?.map((r) => r.role) ?? [] });
  }
});

// src/lib/mcp/tools/list_classes.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_classes_default = defineTool2({
  name: "list_classes",
  title: "\u0421\u044B\u043D\u044B\u043F\u0442\u0430\u0440\u0434\u044B \u0442\u0456\u0437\u0443",
  description: "\u041F\u0430\u0439\u0434\u0430\u043B\u0430\u043D\u0443\u0448\u044B\u043D\u044B\u04A3 \u043C\u0435\u043A\u0442\u0435\u0431\u0456\u043D\u0434\u0435\u0433\u0456 \u0441\u044B\u043D\u044B\u043F\u0442\u0430\u0440\u0434\u044B\u04A3 \u0442\u0456\u0437\u0456\u043C\u0456\u043D \u049B\u0430\u0439\u0442\u0430\u0440\u0430\u0434\u044B (RLS \u0430\u0432\u0442\u043E\u043C\u0430\u0442\u0442\u044B \u049B\u043E\u043B\u0434\u0430\u043D\u044B\u043B\u0430\u0434\u044B).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return textResult("\u0410\u0443\u0442\u0435\u043D\u0442\u0438\u0444\u0438\u043A\u0430\u0446\u0438\u044F \u049B\u0430\u0436\u0435\u0442.", true);
    const { data, error } = await supabaseForUser(ctx).from("classes").select("id, name, grade, letter, teacher_id").order("grade", { ascending: true });
    if (error) return textResult(error.message, true);
    return jsonResult(data ?? []);
  }
});

// src/lib/mcp/tools/list_students.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
var list_students_default = defineTool3({
  name: "list_students",
  title: "\u041E\u049B\u0443\u0448\u044B\u043B\u0430\u0440\u0434\u044B \u0442\u0456\u0437\u0443",
  description: "\u041C\u0435\u043A\u0442\u0435\u043F\u0442\u0435\u0433\u0456 \u043E\u049B\u0443\u0448\u044B\u043B\u0430\u0440\u0434\u044B \u0442\u0456\u0437\u0435\u0434\u0456. \u049A\u043E\u0441\u044B\u043C\u0448\u0430: \u043A\u043B\u0430\u0441\u0441 \u0430\u0442\u0430\u0443\u044B \u0431\u043E\u0439\u044B\u043D\u0448\u0430 \u0441\u04AF\u0437\u0443 (\u043C\u044B\u0441\u0430\u043B\u044B, '7 \u0413').",
  inputSchema: {
    class_name: z.string().optional().describe("\u041A\u043B\u0430\u0441\u0441 \u0430\u0442\u0430\u0443\u044B \u0431\u043E\u0439\u044B\u043D\u0448\u0430 \u0441\u04AF\u0437\u0433\u0456, \u043C\u044B\u0441\u0430\u043B\u044B '7 \u0413'"),
    limit: z.number().int().min(1).max(500).optional().describe("\u0416\u0430\u0437\u0431\u0430 \u0441\u0430\u043D\u044B (\u04D9\u0434\u0435\u043F\u043A\u0456 100)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ class_name, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return textResult("\u0410\u0443\u0442\u0435\u043D\u0442\u0438\u0444\u0438\u043A\u0430\u0446\u0438\u044F \u049B\u0430\u0436\u0435\u0442.", true);
    let q = supabaseForUser(ctx).from("alphabet_book").select("id, order_no, last_name, first_name, class_name, gender, birth_date, program_type, status").order("class_name", { ascending: true }).limit(limit ?? 100);
    if (class_name) q = q.eq("class_name", class_name);
    const { data, error } = await q;
    if (error) return textResult(error.message, true);
    return jsonResult(data ?? []);
  }
});

// src/lib/mcp/tools/list_announcements.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_announcements_default = defineTool4({
  name: "list_announcements",
  title: "\u0425\u0430\u0431\u0430\u0440\u043B\u0430\u043D\u0434\u044B\u0440\u0443\u043B\u0430\u0440\u0434\u044B \u0442\u0456\u0437\u0443",
  description: "\u041C\u0435\u043A\u0442\u0435\u043F\u0442\u0435\u0433\u0456 \u0441\u043E\u04A3\u0493\u044B \u0445\u0430\u0431\u0430\u0440\u043B\u0430\u043D\u0434\u044B\u0440\u0443\u043B\u0430\u0440\u0434\u044B \u049B\u0430\u0439\u0442\u0430\u0440\u0430\u0434\u044B.",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).optional().describe("\u0416\u0430\u0437\u0431\u0430 \u0441\u0430\u043D\u044B (\u04D9\u0434\u0435\u043F\u043A\u0456 20)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return textResult("\u0410\u0443\u0442\u0435\u043D\u0442\u0438\u0444\u0438\u043A\u0430\u0446\u0438\u044F \u049B\u0430\u0436\u0435\u0442.", true);
    const { data, error } = await supabaseForUser(ctx).from("announcements").select("id, title, body, target_role, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return textResult(error.message, true);
    return jsonResult(data ?? []);
  }
});

// src/lib/mcp/tools/create_announcement.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
var create_announcement_default = defineTool5({
  name: "create_announcement",
  title: "\u0425\u0430\u0431\u0430\u0440\u043B\u0430\u043D\u0434\u044B\u0440\u0443 \u049B\u04B1\u0440\u0443",
  description: "\u041F\u0430\u0439\u0434\u0430\u043B\u0430\u043D\u0443\u0448\u044B \u043C\u0435\u043A\u0442\u0435\u0431\u0456\u043D\u0435 \u0430\u0440\u043D\u0430\u043B\u0493\u0430\u043D \u0436\u0430\u04A3\u0430 \u0445\u0430\u0431\u0430\u0440\u043B\u0430\u043D\u0434\u044B\u0440\u0443 \u049B\u04B1\u0440\u0430\u0434\u044B. \u0422\u0435\u043A \u0440\u04B1\u049B\u0441\u0430\u0442\u044B \u0431\u0430\u0440 \u0440\u04E9\u043B\u0434\u0435\u0440 \u04AF\u0448\u0456\u043D (RLS \u0442\u0435\u043A\u0441\u0435\u0440\u0435\u0434\u0456).",
  inputSchema: {
    title: z3.string().min(1).describe("\u0425\u0430\u0431\u0430\u0440\u043B\u0430\u043D\u0434\u044B\u0440\u0443 \u0442\u0430\u049B\u044B\u0440\u044B\u0431\u044B"),
    body: z3.string().min(1).describe("\u0425\u0430\u0431\u0430\u0440\u043B\u0430\u043D\u0434\u044B\u0440\u0443 \u043C\u04D9\u0442\u0456\u043D\u0456"),
    target_role: z3.string().optional().describe("\u041C\u0430\u049B\u0441\u0430\u0442\u0442\u044B \u0440\u04E9\u043B (all, teacher, student, parent...)")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, body, target_role }, ctx) => {
    if (!ctx.isAuthenticated()) return textResult("\u0410\u0443\u0442\u0435\u043D\u0442\u0438\u0444\u0438\u043A\u0430\u0446\u0438\u044F \u049B\u0430\u0436\u0435\u0442.", true);
    const sb = supabaseForUser(ctx);
    const { data: prof } = await sb.from("profiles").select("school_id").eq("user_id", ctx.getUserId()).maybeSingle();
    if (!prof?.school_id) return textResult("\u041F\u0430\u0439\u0434\u0430\u043B\u0430\u043D\u0443\u0448\u044B \u043C\u0435\u043A\u0442\u0435\u043F\u043A\u0435 \u0442\u0456\u0440\u043A\u0435\u043B\u043C\u0435\u0433\u0435\u043D.", true);
    const { data, error } = await sb.from("announcements").insert({
      title,
      body,
      target_role: target_role ?? "all",
      school_id: prof.school_id,
      created_by: ctx.getUserId()
    }).select().maybeSingle();
    if (error) return textResult(error.message, true);
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/list_schedule.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^4.4.3";
var list_schedule_default = defineTool6({
  name: "list_schedule",
  title: "\u0421\u0430\u0431\u0430\u049B \u043A\u0435\u0441\u0442\u0435\u0441\u0456",
  description: "\u041A\u043B\u0430\u0441\u0441 \u043D\u0435\u043C\u0435\u0441\u0435 \u043C\u04B1\u0493\u0430\u043B\u0456\u043C \u0431\u043E\u0439\u044B\u043D\u0448\u0430 \u0441\u0430\u0431\u0430\u049B \u043A\u0435\u0441\u0442\u0435\u0441\u0456\u043D \u049B\u0430\u0439\u0442\u0430\u0440\u0430\u0434\u044B.",
  inputSchema: {
    class_name: z4.string().optional().describe("\u041A\u043B\u0430\u0441\u0441 \u0430\u0442\u0430\u0443\u044B, \u043C\u044B\u0441\u0430\u043B\u044B '7 \u0413'")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ class_name }, ctx) => {
    if (!ctx.isAuthenticated()) return textResult("\u0410\u0443\u0442\u0435\u043D\u0442\u0438\u0444\u0438\u043A\u0430\u0446\u0438\u044F \u049B\u0430\u0436\u0435\u0442.", true);
    let q = supabaseForUser(ctx).from("schedules").select("id, class_name, day_of_week, lesson_number, subject, teacher_name, room").order("day_of_week", { ascending: true }).order("lesson_number", { ascending: true });
    if (class_name) q = q.eq("class_name", class_name);
    const { data, error } = await q.limit(300);
    if (error) return textResult(error.message, true);
    return jsonResult(data ?? []);
  }
});

// src/lib/mcp/tools/list_grades.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^4.4.3";
var list_grades_default = defineTool7({
  name: "list_grades",
  title: "\u0411\u0430\u0493\u0430\u043B\u0430\u0440\u0434\u044B \u049B\u0430\u0440\u0430\u0443",
  description: "\u0410\u0493\u044B\u043C\u0434\u0430\u0493\u044B \u043F\u0430\u0439\u0434\u0430\u043B\u0430\u043D\u0443\u0448\u044B \u04AF\u0448\u0456\u043D \u043A\u04E9\u0440\u0456\u043D\u0435\u0442\u0456\u043D \u0431\u0430\u0493\u0430\u043B\u0430\u0440\u0434\u044B \u049B\u0430\u0439\u0442\u0430\u0440\u0430\u0434\u044B (RLS \u0448\u0435\u043A\u0442\u0435\u0443\u043B\u0435\u0440\u0456).",
  inputSchema: {
    student_id: z5.string().uuid().optional().describe("\u041D\u0430\u049B\u0442\u044B \u043E\u049B\u0443\u0448\u044B\u043D\u044B\u04A3 user_id-\u0456"),
    limit: z5.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ student_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return textResult("\u0410\u0443\u0442\u0435\u043D\u0442\u0438\u0444\u0438\u043A\u0430\u0446\u0438\u044F \u049B\u0430\u0436\u0435\u0442.", true);
    let q = supabaseForUser(ctx).from("grades").select("id, student_id, subject, grade, date, comment").order("date", { ascending: false }).limit(limit ?? 50);
    if (student_id) q = q.eq("student_id", student_id);
    const { data, error } = await q;
    if (error) return textResult(error.message, true);
    return jsonResult(data ?? []);
  }
});

// src/lib/mcp/tools/list_homework.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z6 } from "npm:zod@^4.4.3";
var list_homework_default = defineTool8({
  name: "list_homework",
  title: "\u04AE\u0439 \u0442\u0430\u043F\u0441\u044B\u0440\u043C\u0430\u043B\u0430\u0440\u044B",
  description: "\u041A\u043B\u0430\u0441\u0441/\u043F\u04D9\u043D \u0431\u043E\u0439\u044B\u043D\u0448\u0430 \u04AF\u0439 \u0442\u0430\u043F\u0441\u044B\u0440\u043C\u0430\u043B\u0430\u0440\u044B\u043D\u044B\u04A3 \u0442\u0456\u0437\u0456\u043C\u0456\u043D \u049B\u0430\u0439\u0442\u0430\u0440\u0430\u0434\u044B.",
  inputSchema: {
    class_name: z6.string().optional(),
    subject: z6.string().optional(),
    limit: z6.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ class_name, subject, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return textResult("\u0410\u0443\u0442\u0435\u043D\u0442\u0438\u0444\u0438\u043A\u0430\u0446\u0438\u044F \u049B\u0430\u0436\u0435\u0442.", true);
    let q = supabaseForUser(ctx).from("homework").select("id, class_name, subject, title, description, due_date, created_at").order("due_date", { ascending: false }).limit(limit ?? 50);
    if (class_name) q = q.eq("class_name", class_name);
    if (subject) q = q.eq("subject", subject);
    const { data, error } = await q;
    if (error) return textResult(error.message, true);
    return jsonResult(data ?? []);
  }
});

// src/lib/mcp/tools/school_stats.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.24.0";
var school_stats_default = defineTool9({
  name: "school_stats",
  title: "\u041C\u0435\u043A\u0442\u0435\u043F \u0441\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043A\u0430\u0441\u044B",
  description: "\u041F\u0430\u0439\u0434\u0430\u043B\u0430\u043D\u0443\u0448\u044B \u043C\u0435\u043A\u0442\u0435\u0431\u0456\u043D\u0456\u04A3 \u0436\u0430\u043B\u043F\u044B \u0441\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043A\u0430\u0441\u044B\u043D: \u043E\u049B\u0443\u0448\u044B, \u043C\u04B1\u0493\u0430\u043B\u0456\u043C, \u0441\u044B\u043D\u044B\u043F \u0441\u0430\u043D\u044B\u043D \u049B\u0430\u0439\u0442\u0430\u0440\u0430\u0434\u044B.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return textResult("\u0410\u0443\u0442\u0435\u043D\u0442\u0438\u0444\u0438\u043A\u0430\u0446\u0438\u044F \u049B\u0430\u0436\u0435\u0442.", true);
    const sb = supabaseForUser(ctx);
    const [students, teachers, classes, announcements] = await Promise.all([
      sb.from("alphabet_book").select("*", { count: "exact", head: true }),
      sb.from("profiles").select("*", { count: "exact", head: true }),
      sb.from("classes").select("*", { count: "exact", head: true }),
      sb.from("announcements").select("*", { count: "exact", head: true })
    ]);
    return jsonResult({
      students: students.count ?? 0,
      profiles: teachers.count ?? 0,
      classes: classes.count ?? 0,
      announcements: announcements.count ?? 0
    });
  }
});

// src/lib/mcp/index.ts
var projectRef = "sbsxehdtlmkvopforfdy";
var mcp_default = defineMcp({
  name: "bilimapp-mcp",
  title: "BilimApp",
  version: "0.1.0",
  instructions: "BilimApp \u0431\u0456\u043B\u0456\u043C \u0431\u0435\u0440\u0443 \u043F\u043B\u0430\u0442\u0444\u043E\u0440\u043C\u0430\u0441\u044B\u043D\u044B\u04A3 MCP \u0441\u0435\u0440\u0432\u0435\u0440\u043B\u0435\u0440\u0456. \u0410\u0493\u044B\u043C\u0434\u0430\u0493\u044B \u049B\u043E\u0441\u044B\u043B\u0493\u0430\u043D \u043F\u0430\u0439\u0434\u0430\u043B\u0430\u043D\u0443\u0448\u044B\u043D\u044B\u04A3 \u0430\u0442\u044B\u043D\u0430\u043D \u043C\u0435\u043A\u0442\u0435\u043F \u0434\u0435\u0440\u0435\u043A\u0442\u0435\u0440\u0456\u043D\u0435 (\u0441\u044B\u043D\u044B\u043F\u0442\u0430\u0440, \u043E\u049B\u0443\u0448\u044B\u043B\u0430\u0440, \u0441\u0430\u0431\u0430\u049B \u043A\u0435\u0441\u0442\u0435\u0441\u0456, \u0431\u0430\u0493\u0430\u043B\u0430\u0440, \u04AF\u0439 \u0442\u0430\u043F\u0441\u044B\u0440\u043C\u0430\u043B\u0430\u0440\u044B, \u0445\u0430\u0431\u0430\u0440\u043B\u0430\u043D\u0434\u044B\u0440\u0443\u043B\u0430\u0440) \u049B\u043E\u043B \u0436\u0435\u0442\u043A\u0456\u0437\u0443 \u0436\u04D9\u043D\u0435 \u0445\u0430\u0431\u0430\u0440\u043B\u0430\u043D\u0434\u044B\u0440\u0443 \u0436\u0430\u0440\u0438\u044F\u043B\u0430\u0443 \u043C\u04AF\u043C\u043A\u0456\u043D\u0434\u0456\u043A\u0442\u0435\u0440\u0456\u043D \u04B1\u0441\u044B\u043D\u0430\u0434\u044B. \u0411\u0430\u0440\u043B\u044B\u049B \u049B\u043E\u043B \u0436\u0435\u0442\u043A\u0456\u0437\u0443\u043B\u0435\u0440 RLS \u0430\u0440\u049B\u044B\u043B\u044B \u043F\u0430\u0439\u0434\u0430\u043B\u0430\u043D\u0443\u0448\u044B\u043D\u044B\u04A3 \u0440\u04E9\u043B\u0456 \u043C\u0435\u043D \u043C\u0435\u043A\u0442\u0435\u0431\u0456\u043D\u0435 \u0441\u04D9\u0439\u043A\u0435\u0441 \u0448\u0435\u043A\u0442\u0435\u043B\u0435\u0434\u0456.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_my_profile_default,
    school_stats_default,
    list_classes_default,
    list_students_default,
    list_schedule_default,
    list_grades_default,
    list_homework_default,
    list_announcements_default,
    create_announcement_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
